2025-02-25 20:40:11,619 - ERROR - Error adding name plate: images do not match
2025-02-25 20:40:12,141 - INFO - Saved card: output\Rita.png
2025-02-25 20:40:12,337 - ERROR - Error adding name plate: images do not match
2025-02-25 20:40:12,968 - INFO - Saved card: output\Kita.png
2025-02-25 20:40:13,163 - ERROR - Error adding name plate: images do not match
2025-02-25 20:40:13,790 - INFO - Saved card: output\Ronw.png
2025-02-25 21:28:07,986 - ERROR - Error adding name plate: images do not match
2025-02-25 21:28:08,555 - INFO - Saved card: output\Rita.png
2025-02-25 21:28:08,752 - ERROR - Error adding name plate: images do not match
2025-02-25 21:28:09,352 - INFO - Saved card: output\Kita.png
2025-02-25 21:28:09,545 - ERROR - Error adding name plate: images do not match
2025-02-25 21:28:10,147 - INFO - Saved card: output\Ronw.png
2025-02-25 21:33:41,130 - ERROR - Error adding name plate: images do not match
2025-02-25 21:33:41,601 - INFO - Saved card: output\Rita.png
2025-02-25 21:33:41,769 - ERROR - Error adding name plate: images do not match
2025-02-25 21:33:42,332 - INFO - Saved card: output\Kita.png
2025-02-25 21:33:42,501 - ERROR - Error adding name plate: images do not match
2025-02-25 21:33:43,079 - INFO - Saved card: output\Ronw.png
2025-02-25 21:38:24,265 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:24,287 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:24,308 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:24,328 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:24,349 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:24,375 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 21:38:24,855 - INFO - Saved card: output\Rita.png
2025-02-25 21:38:24,925 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:24,945 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:24,965 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:24,985 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:25,005 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:25,031 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 21:38:25,595 - INFO - Saved card: output\Kita.png
2025-02-25 21:38:25,666 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:25,686 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:25,706 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:25,727 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:25,746 - WARNING - Bold font not found, using regular font.
2025-02-25 21:38:25,772 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 21:38:26,353 - INFO - Saved card: output\Ronw.png
2025-02-25 21:43:51,955 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:51,975 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:51,995 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:52,015 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:52,036 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:52,062 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 21:43:52,537 - INFO - Saved card: output\Rita.png
2025-02-25 21:43:52,606 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:52,627 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:52,646 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:52,667 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:52,687 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:52,713 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 21:43:53,272 - INFO - Saved card: output\Kita.png
2025-02-25 21:43:53,342 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:53,362 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:53,382 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:53,402 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:53,422 - WARNING - Bold font not found, using regular font.
2025-02-25 21:43:53,448 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 21:43:54,024 - INFO - Saved card: output\Ronw.png
2025-02-25 22:33:32,585 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:32,605 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:32,635 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:32,656 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:32,677 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:32,714 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:33:33,218 - INFO - Saved card: output\Rita.png
2025-02-25 22:33:33,302 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:33,323 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:33,343 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:33,365 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:33,396 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:33,424 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:33:34,047 - INFO - Saved card: output\Kita.png
2025-02-25 22:33:34,130 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:34,154 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:34,175 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:34,195 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:34,218 - WARNING - Bold font not found, using regular font.
2025-02-25 22:33:34,247 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:33:34,874 - INFO - Saved card: output\Ronw.png
2025-02-25 22:34:55,942 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:55,964 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:55,984 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:56,009 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:56,034 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:56,062 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:34:56,571 - INFO - Saved card: output\Rita.png
2025-02-25 22:34:56,648 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:56,669 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:56,693 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:56,715 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:56,740 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:56,767 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:34:57,350 - INFO - Saved card: output\Kita.png
2025-02-25 22:34:57,422 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:57,447 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:57,467 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:57,489 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:57,510 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:57,537 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:34:58,097 - INFO - Saved card: output\Ronw.png
2025-02-25 22:34:58,211 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:58,267 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:58,333 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:58,364 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:58,416 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:58,453 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:34:58,937 - INFO - Saved card: output\Anki.png
2025-02-25 22:34:59,059 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:59,118 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:59,180 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:59,205 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:59,250 - WARNING - Bold font not found, using regular font.
2025-02-25 22:34:59,277 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:34:59,841 - INFO - Saved card: output\Oria.png
2025-02-25 22:34:59,960 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:00,011 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:00,066 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:00,093 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:00,138 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:00,169 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:35:00,765 - INFO - Saved card: output\Xieu.png
2025-02-25 22:35:59,843 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:59,863 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:59,884 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:59,905 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:59,926 - WARNING - Bold font not found, using regular font.
2025-02-25 22:35:59,952 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:36:00,448 - INFO - Saved card: output\Rita.png
2025-02-25 22:36:00,525 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:00,548 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:00,569 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:00,604 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:00,626 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:00,652 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:36:01,239 - INFO - Saved card: output\Kita.png
2025-02-25 22:36:01,313 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:01,333 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:01,354 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:01,373 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:01,405 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:01,432 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:36:02,009 - INFO - Saved card: output\Ronw.png
2025-02-25 22:36:02,113 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:02,161 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:02,218 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:02,243 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:02,288 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:02,316 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:36:02,793 - INFO - Saved card: output\Anki.png
2025-02-25 22:36:02,906 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:02,964 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:03,017 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:03,043 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:03,093 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:03,119 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:36:03,698 - INFO - Saved card: output\Oria.png
2025-02-25 22:36:03,811 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:03,860 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:03,915 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:03,940 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:03,984 - WARNING - Bold font not found, using regular font.
2025-02-25 22:36:04,011 - ERROR - Error adding name plate: 'ImageDraw' object has no attribute 'textsize'
2025-02-25 22:36:04,564 - INFO - Saved card: output\Xieu.png
2025-02-25 22:41:55,425 - INFO - Saved card: output\Rita.png
2025-02-25 22:41:56,196 - INFO - Saved card: output\Kita.png
2025-02-25 22:41:56,971 - INFO - Saved card: output\Ronw.png
2025-02-25 22:41:57,773 - INFO - Saved card: output\Anki.png
2025-02-25 22:41:58,683 - INFO - Saved card: output\Oria.png
2025-02-25 22:41:59,547 - INFO - Saved card: output\Xieu.png
2025-02-25 23:09:20,739 - INFO - Saved card: output\Rita.png
2025-02-25 23:09:21,479 - INFO - Saved card: output\Kita.png
2025-02-25 23:09:22,223 - INFO - Saved card: output\Ronw.png
2025-02-25 23:09:23,007 - INFO - Saved card: output\Anki.png
2025-02-25 23:09:23,891 - INFO - Saved card: output\Oria.png
2025-02-25 23:09:24,766 - INFO - Saved card: output\Xieu.png
2025-02-25 23:09:53,667 - INFO - Saved card: output\Rita.png
2025-02-25 23:09:54,430 - INFO - Saved card: output\Kita.png
2025-02-25 23:09:55,172 - INFO - Saved card: output\Ronw.png
2025-02-25 23:09:55,956 - INFO - Saved card: output\Anki.png
2025-02-25 23:09:56,843 - INFO - Saved card: output\Oria.png
2025-02-25 23:09:57,711 - INFO - Saved card: output\Xieu.png
2025-02-25 23:15:00,224 - INFO - Saved card: output\Rita.png
2025-02-25 23:15:00,967 - INFO - Saved card: output\Kita.png
2025-02-25 23:15:01,686 - INFO - Saved card: output\Ronw.png
2025-02-25 23:15:02,444 - INFO - Saved card: output\Anki.png
2025-02-25 23:15:03,304 - INFO - Saved card: output\Oria.png
2025-02-25 23:15:04,161 - INFO - Saved card: output\Xieu.png
2025-02-25 23:20:37,403 - INFO - Saved card: output\Rita.png
2025-02-25 23:20:38,174 - INFO - Saved card: output\Kita.png
2025-02-25 23:20:38,930 - INFO - Saved card: output\Ronw.png
2025-02-25 23:20:39,750 - INFO - Saved card: output\Anki.png
2025-02-25 23:20:40,638 - INFO - Saved card: output\Oria.png
2025-02-25 23:20:41,496 - INFO - Saved card: output\Xieu.png
2025-02-25 23:20:42,333 - INFO - Saved card: output\Tarczolud.png
2025-02-25 23:27:27,060 - ERROR - Failed to generate card for Rita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:27:27,151 - ERROR - Failed to generate card for Kita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:27:27,241 - ERROR - Failed to generate card for Ronw
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:27:27,395 - ERROR - Failed to generate card for Anki
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:27:27,563 - ERROR - Failed to generate card for Oria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:27:27,721 - ERROR - Failed to generate card for Xieu
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:27:27,877 - ERROR - Failed to generate card for Tarczolud
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:27:59,690 - ERROR - Failed to generate card for Rita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:27:59,782 - ERROR - Failed to generate card for Kita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:27:59,873 - ERROR - Failed to generate card for Ronw
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:00,028 - ERROR - Failed to generate card for Anki
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:00,201 - ERROR - Failed to generate card for Oria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:00,362 - ERROR - Failed to generate card for Xieu
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:00,521 - ERROR - Failed to generate card for Tarczolud
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:24,231 - INFO - Saved card: output\Rita.png
2025-02-25 23:28:24,974 - INFO - Saved card: output\Kita.png
2025-02-25 23:28:25,699 - INFO - Saved card: output\Ronw.png
2025-02-25 23:28:26,482 - INFO - Saved card: output\Anki.png
2025-02-25 23:28:27,365 - INFO - Saved card: output\Oria.png
2025-02-25 23:28:28,222 - INFO - Saved card: output\Xieu.png
2025-02-25 23:28:29,052 - INFO - Saved card: output\Tarczolud.png
2025-02-25 23:28:35,172 - ERROR - Failed to generate card for Rita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:35,262 - ERROR - Failed to generate card for Kita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:35,355 - ERROR - Failed to generate card for Ronw
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:35,512 - ERROR - Failed to generate card for Anki
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:35,681 - ERROR - Failed to generate card for Oria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:35,842 - ERROR - Failed to generate card for Xieu
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:28:36,001 - ERROR - Failed to generate card for Tarczolud
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:29:07,322 - ERROR - Failed to generate card for Rita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armor(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RPGCardGenerator._add_armor() missing 2 required positional arguments: 'value' and 'position'
2025-02-25 23:29:07,412 - ERROR - Failed to generate card for Kita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armor(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RPGCardGenerator._add_armor() missing 2 required positional arguments: 'value' and 'position'
2025-02-25 23:29:07,502 - ERROR - Failed to generate card for Ronw
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armor(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RPGCardGenerator._add_armor() missing 2 required positional arguments: 'value' and 'position'
2025-02-25 23:29:07,654 - ERROR - Failed to generate card for Anki
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armor(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RPGCardGenerator._add_armor() missing 2 required positional arguments: 'value' and 'position'
2025-02-25 23:29:07,819 - ERROR - Failed to generate card for Oria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armor(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RPGCardGenerator._add_armor() missing 2 required positional arguments: 'value' and 'position'
2025-02-25 23:29:07,976 - ERROR - Failed to generate card for Xieu
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armor(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RPGCardGenerator._add_armor() missing 2 required positional arguments: 'value' and 'position'
2025-02-25 23:29:08,132 - ERROR - Failed to generate card for Tarczolud
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armor(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RPGCardGenerator._add_armor() missing 2 required positional arguments: 'value' and 'position'
2025-02-25 23:30:11,863 - INFO - Saved card: output\Rita.png
2025-02-25 23:30:12,603 - INFO - Saved card: output\Kita.png
2025-02-25 23:30:13,320 - INFO - Saved card: output\Ronw.png
2025-02-25 23:30:14,088 - INFO - Saved card: output\Anki.png
2025-02-25 23:30:14,950 - INFO - Saved card: output\Oria.png
2025-02-25 23:30:15,829 - INFO - Saved card: output\Xieu.png
2025-02-25 23:30:16,680 - INFO - Saved card: output\Tarczolud.png
2025-02-25 23:30:32,293 - INFO - Saved card: output\Rita.png
2025-02-25 23:30:33,050 - INFO - Saved card: output\Kita.png
2025-02-25 23:30:33,782 - INFO - Saved card: output\Ronw.png
2025-02-25 23:30:34,556 - INFO - Saved card: output\Anki.png
2025-02-25 23:30:35,441 - INFO - Saved card: output\Oria.png
2025-02-25 23:30:36,296 - INFO - Saved card: output\Xieu.png
2025-02-25 23:30:37,123 - INFO - Saved card: output\Tarczolud.png
2025-02-25 23:30:37,284 - ERROR - Armor image not found: alt06
2025-02-25 23:30:37,284 - ERROR - Armor image not found: 00802--2074780840-fantaC_v10-Euler-21-7.6
2025-02-25 23:30:37,911 - INFO - Saved card: output\Reria.png
2025-02-25 23:34:03,786 - ERROR - Failed to generate card for Rita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:34:03,877 - ERROR - Failed to generate card for Kita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:34:03,968 - ERROR - Failed to generate card for Ronw
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:34:04,122 - ERROR - Failed to generate card for Anki
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:34:04,293 - ERROR - Failed to generate card for Oria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:34:04,456 - ERROR - Failed to generate card for Xieu
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:34:04,614 - ERROR - Failed to generate card for Tarczolud
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:34:04,772 - ERROR - Failed to generate card for Reria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 127, in _add_combat_elements
    card = self._add_armors(card, data)
           ^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_armors'. Did you mean: '_add_armor'?
2025-02-25 23:37:19,547 - ERROR - Failed to generate card for Rita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:19,599 - ERROR - Failed to generate card for Kita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:19,651 - ERROR - Failed to generate card for Ronw
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:19,701 - ERROR - Failed to generate card for Anki
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:19,752 - ERROR - Failed to generate card for Oria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:19,803 - ERROR - Failed to generate card for Xieu
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:19,852 - ERROR - Failed to generate card for Tarczolud
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:19,900 - ERROR - Failed to generate card for Reria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:43,894 - ERROR - Failed to generate card for Rita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:43,946 - ERROR - Failed to generate card for Kita
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:43,996 - ERROR - Failed to generate card for Ronw
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:44,045 - ERROR - Failed to generate card for Anki
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:44,096 - ERROR - Failed to generate card for Oria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:44,145 - ERROR - Failed to generate card for Xieu
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:44,195 - ERROR - Failed to generate card for Tarczolud
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:37:44,243 - ERROR - Failed to generate card for Reria
Traceback (most recent call last):
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 75, in generate_from_file
    card = self._create_card(row)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 102, in _create_card
    card = self._add_combat_elements(card, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!Skrypty\CharacterCardGenerator\main.py", line 126, in _add_combat_elements
    card = self._add_weapons(card, data)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'RPGCardGenerator' object has no attribute '_add_weapons'. Did you mean: '_add_weapon'?
2025-02-25 23:38:09,535 - INFO - Saved card: output\Rita.png
2025-02-25 23:38:10,293 - INFO - Saved card: output\Kita.png
2025-02-25 23:38:11,024 - INFO - Saved card: output\Ronw.png
2025-02-25 23:38:11,802 - INFO - Saved card: output\Anki.png
2025-02-25 23:38:12,667 - INFO - Saved card: output\Oria.png
2025-02-25 23:38:13,523 - INFO - Saved card: output\Xieu.png
2025-02-25 23:38:14,349 - INFO - Saved card: output\Tarczolud.png
2025-02-25 23:38:14,503 - ERROR - Armor image not found: alt06
2025-02-25 23:38:14,504 - ERROR - Armor image not found: 00802--2074780840-fantaC_v10-Euler-21-7.6
2025-02-25 23:38:15,122 - INFO - Saved card: output\Reria.png
2025-02-25 23:39:03,616 - INFO - Saved card: output\Rita.png
2025-02-25 23:39:04,366 - INFO - Saved card: output\Kita.png
2025-02-25 23:39:05,083 - INFO - Saved card: output\Ronw.png
2025-02-25 23:39:05,845 - INFO - Saved card: output\Anki.png
2025-02-25 23:39:06,704 - INFO - Saved card: output\Oria.png
2025-02-25 23:39:07,580 - INFO - Saved card: output\Xieu.png
2025-02-25 23:39:08,429 - INFO - Saved card: output\Tarczolud.png
2025-02-25 23:39:08,641 - ERROR - Armor image not found: 00802--2074780840-fantaC_v10-Euler-21-7.6
2025-02-25 23:39:09,277 - INFO - Saved card: output\Reria.png
2025-02-25 23:39:32,335 - INFO - Saved card: output\Rita.png
2025-02-25 23:39:33,076 - INFO - Saved card: output\Kita.png
2025-02-25 23:39:33,813 - INFO - Saved card: output\Ronw.png
2025-02-25 23:39:34,596 - INFO - Saved card: output\Anki.png
2025-02-25 23:39:35,484 - INFO - Saved card: output\Oria.png
2025-02-25 23:39:36,345 - INFO - Saved card: output\Xieu.png
2025-02-25 23:39:37,175 - INFO - Saved card: output\Tarczolud.png
2025-02-25 23:39:38,022 - INFO - Saved card: output\Reria.png
2025-02-26 10:08:14,136 - INFO - Saved card: output\Rita.png
2025-02-26 10:08:14,253 - ERROR - Weapon image not found: explosives
2025-02-26 10:08:15,150 - INFO - Saved card: output\Kita.png
2025-02-26 10:08:16,160 - INFO - Saved card: output\Ronw.png
2025-02-26 10:08:17,308 - INFO - Saved card: output\Anki.png
2025-02-26 10:08:18,544 - INFO - Saved card: output\Oria.png
2025-02-26 10:08:19,787 - INFO - Saved card: output\Xieu.png
2025-02-26 10:08:20,977 - INFO - Saved card: output\Tarczolud.png
2025-02-26 10:08:22,255 - INFO - Saved card: output\Reria.png
2025-02-26 10:09:23,291 - INFO - Saved card: output\Rita.png
2025-02-26 10:09:24,311 - INFO - Saved card: output\Kita.png
2025-02-26 10:09:25,300 - INFO - Saved card: output\Ronw.png
2025-02-26 10:09:26,412 - INFO - Saved card: output\Anki.png
2025-02-26 10:09:27,687 - INFO - Saved card: output\Oria.png
2025-02-26 10:09:29,018 - INFO - Saved card: output\Xieu.png
2025-02-26 10:09:30,297 - INFO - Saved card: output\Tarczolud.png
2025-02-26 10:09:31,625 - INFO - Saved card: output\Reria.png
